name: Test

on:
  push:
    paths:
      - '.github/workflows/test.yml'
      - '**/*.swift'
  pull_request:
    paths:
      - '.github/workflows/test.yml'
      - '**/*.swift'

jobs:
  swift-test:
    strategy:
      fail-fast: false
      matrix:
        operating-system: [macOS-latest]
        swift-version: ["5.3.0", "5.3.1", "5.3.2"]
    runs-on: ${{ matrix.operating-system }}
    env:
      SWIFT_VERSION: ${{ matrix.swift-version }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Swift
        run: |
          git clone https://github.com/kylef/swiftenv.git ~/.swiftenv

          export SWIFTENV_ROOT="$HOME/.swiftenv"
          export PATH="$SWIFTENV_ROOT/bin:$SWIFTENV_ROOT/shims:$PATH"

          echo 'export SWIFTENV_ROOT="$HOME/.swiftenv"' >> ~/.bash_profile
          echo 'export PATH="$SWIFTENV_ROOT/bin:$PATH"' >> ~/.bash_profile
          echo 'eval "$(swiftenv init -)"' >> ~/.bash_profile

          swiftenv install -s
      - run: eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
      - name: Build
        run: swift build -v
      - name: Run tests
        run: swift test -v
  xcode-test:
    strategy:
      fail-fast: false
      matrix:
        xcode-version: ["12.0.1", "12.4"]
        xcode-destination: [
          "platform=OS X,arch=x86_64",
          "platform=OS X,arch=x86_64,variant=Mac Catalyst",
          "platform=iOS Simulator,name=iPhone 11 Pro,OS=latest",
          "platform=tvOS Simulator,name=Apple TV 4K,OS=latest",
          "platform=watchOS Simulator,name=Apple Watch Series 6 - 44mm,OS=latest",
        ]
        exclude:
          - xcode-version: 12.0.1
            xcode-destination: "platform=watchOS Simulator,name=Apple Watch Series 6 - 44mm,OS=latest"
          - xcode-version: 12.4
            xcode-destination: "platform=watchOS Simulator,name=Apple Watch Series 6 - 44mm,OS=latest"
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: sinoru/actions-setup-xcode@v1.1
        with:
          xcode-version: ${{ matrix.xcode-version }}
          apple-id: bot@sinoru.io
          apple-id-password: ${{ secrets.APPLE_ID_PASSWORD }}
      - name: Resolve Package Dependencies
        run: xcodebuild -resolvePackageDependencies
      - name: Analyze
        run: xcodebuild -scheme TwitterKit -destination '${{ matrix.xcode-destination }}' analyze
      - name: Test
        run: xcodebuild -scheme TwitterKit -destination '${{ matrix.xcode-destination }}' test
